### ISSUE TITLE
Error DataIncomplete "Unable to resolve all nodes"

### ISSUE THREAD

**Issue by antonykamp** [simulate-digital-rail/orm-importer#50]
No matter which polygon I enter. I currently always get the following error message 😇 

<img width="1124" alt="Screenshot 2023-02-13 at 09 57 44" src="https://user-images.githubusercontent.com/45163503/218414114-f689c3aa-36d2-4ca7-bb3a-7bf841b749d8.png">

**Comment by jeriox** [comment]
This is due to an error in the HPI Overpass Proxy as it seems to return invalid results with those queries since the change of configuration on thursday. Running the query against the official API endpoint yields valid results. You can remove the URL in https://github.com/simulate-digital-rail/orm-importer/blob/main/orm_importer/importer.py#L39 in your local venv as a workaround. Be advised that you may experience more errors due to server overload.

**Comment by antonykamp** [comment]
Thank you very much!

**Comment by lpirl** [comment]
Thanks for reporting – I like ``nginx`` and like gathering experiences with it. :)

During the last configuration changes, I enabled caching of POST requests (e.g., ``overpy`` uses POST, I guess). Turns out, the request body is not part of the cache key by default. This should be fixed now, give it a go.

Feel free to report any more deficiencies so our reverse proxy evolves to a solid service.

**Comment by antonykamp** [comment]
Thanks for the hint and sharing your experience :D @lpirl
